# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/abdu/qt_apps/yocto-gui-cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/abdu/qt_apps/yocto-gui-cmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abdu/qt_apps/yocto-gui-cmake/CMakeFiles /home/abdu/qt_apps/yocto-gui-cmake//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abdu/qt_apps/yocto-gui-cmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yocto-gui-cmake

# Build rule for target.
yocto-gui-cmake: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yocto-gui-cmake
.PHONY : yocto-gui-cmake

# fast build rule for target.
yocto-gui-cmake/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/build
.PHONY : yocto-gui-cmake/fast

#=============================================================================
# Target rules for targets named yocto-gui-cmake_autogen

# Build rule for target.
yocto-gui-cmake_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yocto-gui-cmake_autogen
.PHONY : yocto-gui-cmake_autogen

# fast build rule for target.
yocto-gui-cmake_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake_autogen.dir/build.make CMakeFiles/yocto-gui-cmake_autogen.dir/build
.PHONY : yocto-gui-cmake_autogen/fast

SmartHomeLeds/smarthome_leds.o: SmartHomeLeds/smarthome_leds.cpp.o
.PHONY : SmartHomeLeds/smarthome_leds.o

# target to build an object file
SmartHomeLeds/smarthome_leds.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeLeds/smarthome_leds.cpp.o
.PHONY : SmartHomeLeds/smarthome_leds.cpp.o

SmartHomeLeds/smarthome_leds.i: SmartHomeLeds/smarthome_leds.cpp.i
.PHONY : SmartHomeLeds/smarthome_leds.i

# target to preprocess a source file
SmartHomeLeds/smarthome_leds.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeLeds/smarthome_leds.cpp.i
.PHONY : SmartHomeLeds/smarthome_leds.cpp.i

SmartHomeLeds/smarthome_leds.s: SmartHomeLeds/smarthome_leds.cpp.s
.PHONY : SmartHomeLeds/smarthome_leds.s

# target to generate assembly for a file
SmartHomeLeds/smarthome_leds.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeLeds/smarthome_leds.cpp.s
.PHONY : SmartHomeLeds/smarthome_leds.cpp.s

SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.o: SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.cpp.o
.PHONY : SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.o

# target to build an object file
SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.cpp.o
.PHONY : SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.cpp.o

SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.i: SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.cpp.i
.PHONY : SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.i

# target to preprocess a source file
SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.cpp.i
.PHONY : SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.cpp.i

SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.s: SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.cpp.s
.PHONY : SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.s

# target to generate assembly for a file
SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.cpp.s
.PHONY : SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.cpp.s

SmartHomeTemperature/LCD/LCD.o: SmartHomeTemperature/LCD/LCD.cpp.o
.PHONY : SmartHomeTemperature/LCD/LCD.o

# target to build an object file
SmartHomeTemperature/LCD/LCD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/LCD/LCD.cpp.o
.PHONY : SmartHomeTemperature/LCD/LCD.cpp.o

SmartHomeTemperature/LCD/LCD.i: SmartHomeTemperature/LCD/LCD.cpp.i
.PHONY : SmartHomeTemperature/LCD/LCD.i

# target to preprocess a source file
SmartHomeTemperature/LCD/LCD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/LCD/LCD.cpp.i
.PHONY : SmartHomeTemperature/LCD/LCD.cpp.i

SmartHomeTemperature/LCD/LCD.s: SmartHomeTemperature/LCD/LCD.cpp.s
.PHONY : SmartHomeTemperature/LCD/LCD.s

# target to generate assembly for a file
SmartHomeTemperature/LCD/LCD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/LCD/LCD.cpp.s
.PHONY : SmartHomeTemperature/LCD/LCD.cpp.s

SmartHomeTemperature/Mail/Mail_reaction.o: SmartHomeTemperature/Mail/Mail_reaction.cpp.o
.PHONY : SmartHomeTemperature/Mail/Mail_reaction.o

# target to build an object file
SmartHomeTemperature/Mail/Mail_reaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/Mail/Mail_reaction.cpp.o
.PHONY : SmartHomeTemperature/Mail/Mail_reaction.cpp.o

SmartHomeTemperature/Mail/Mail_reaction.i: SmartHomeTemperature/Mail/Mail_reaction.cpp.i
.PHONY : SmartHomeTemperature/Mail/Mail_reaction.i

# target to preprocess a source file
SmartHomeTemperature/Mail/Mail_reaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/Mail/Mail_reaction.cpp.i
.PHONY : SmartHomeTemperature/Mail/Mail_reaction.cpp.i

SmartHomeTemperature/Mail/Mail_reaction.s: SmartHomeTemperature/Mail/Mail_reaction.cpp.s
.PHONY : SmartHomeTemperature/Mail/Mail_reaction.s

# target to generate assembly for a file
SmartHomeTemperature/Mail/Mail_reaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/Mail/Mail_reaction.cpp.s
.PHONY : SmartHomeTemperature/Mail/Mail_reaction.cpp.s

SmartHomeTemperature/Notifier/Notifier.o: SmartHomeTemperature/Notifier/Notifier.cpp.o
.PHONY : SmartHomeTemperature/Notifier/Notifier.o

# target to build an object file
SmartHomeTemperature/Notifier/Notifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/Notifier/Notifier.cpp.o
.PHONY : SmartHomeTemperature/Notifier/Notifier.cpp.o

SmartHomeTemperature/Notifier/Notifier.i: SmartHomeTemperature/Notifier/Notifier.cpp.i
.PHONY : SmartHomeTemperature/Notifier/Notifier.i

# target to preprocess a source file
SmartHomeTemperature/Notifier/Notifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/Notifier/Notifier.cpp.i
.PHONY : SmartHomeTemperature/Notifier/Notifier.cpp.i

SmartHomeTemperature/Notifier/Notifier.s: SmartHomeTemperature/Notifier/Notifier.cpp.s
.PHONY : SmartHomeTemperature/Notifier/Notifier.s

# target to generate assembly for a file
SmartHomeTemperature/Notifier/Notifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/Notifier/Notifier.cpp.s
.PHONY : SmartHomeTemperature/Notifier/Notifier.cpp.s

SmartHomeTemperature/Observer/Observer.o: SmartHomeTemperature/Observer/Observer.cpp.o
.PHONY : SmartHomeTemperature/Observer/Observer.o

# target to build an object file
SmartHomeTemperature/Observer/Observer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/Observer/Observer.cpp.o
.PHONY : SmartHomeTemperature/Observer/Observer.cpp.o

SmartHomeTemperature/Observer/Observer.i: SmartHomeTemperature/Observer/Observer.cpp.i
.PHONY : SmartHomeTemperature/Observer/Observer.i

# target to preprocess a source file
SmartHomeTemperature/Observer/Observer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/Observer/Observer.cpp.i
.PHONY : SmartHomeTemperature/Observer/Observer.cpp.i

SmartHomeTemperature/Observer/Observer.s: SmartHomeTemperature/Observer/Observer.cpp.s
.PHONY : SmartHomeTemperature/Observer/Observer.s

# target to generate assembly for a file
SmartHomeTemperature/Observer/Observer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/Observer/Observer.cpp.s
.PHONY : SmartHomeTemperature/Observer/Observer.cpp.s

SmartHomeTemperature/WeatherStatus/WeatherStatus.o: SmartHomeTemperature/WeatherStatus/WeatherStatus.cpp.o
.PHONY : SmartHomeTemperature/WeatherStatus/WeatherStatus.o

# target to build an object file
SmartHomeTemperature/WeatherStatus/WeatherStatus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/WeatherStatus/WeatherStatus.cpp.o
.PHONY : SmartHomeTemperature/WeatherStatus/WeatherStatus.cpp.o

SmartHomeTemperature/WeatherStatus/WeatherStatus.i: SmartHomeTemperature/WeatherStatus/WeatherStatus.cpp.i
.PHONY : SmartHomeTemperature/WeatherStatus/WeatherStatus.i

# target to preprocess a source file
SmartHomeTemperature/WeatherStatus/WeatherStatus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/WeatherStatus/WeatherStatus.cpp.i
.PHONY : SmartHomeTemperature/WeatherStatus/WeatherStatus.cpp.i

SmartHomeTemperature/WeatherStatus/WeatherStatus.s: SmartHomeTemperature/WeatherStatus/WeatherStatus.cpp.s
.PHONY : SmartHomeTemperature/WeatherStatus/WeatherStatus.s

# target to generate assembly for a file
SmartHomeTemperature/WeatherStatus/WeatherStatus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/WeatherStatus/WeatherStatus.cpp.s
.PHONY : SmartHomeTemperature/WeatherStatus/WeatherStatus.cpp.s

SmartHomeTemperature/Whatsapp/Whatsapp_reaction.o: SmartHomeTemperature/Whatsapp/Whatsapp_reaction.cpp.o
.PHONY : SmartHomeTemperature/Whatsapp/Whatsapp_reaction.o

# target to build an object file
SmartHomeTemperature/Whatsapp/Whatsapp_reaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/Whatsapp/Whatsapp_reaction.cpp.o
.PHONY : SmartHomeTemperature/Whatsapp/Whatsapp_reaction.cpp.o

SmartHomeTemperature/Whatsapp/Whatsapp_reaction.i: SmartHomeTemperature/Whatsapp/Whatsapp_reaction.cpp.i
.PHONY : SmartHomeTemperature/Whatsapp/Whatsapp_reaction.i

# target to preprocess a source file
SmartHomeTemperature/Whatsapp/Whatsapp_reaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/Whatsapp/Whatsapp_reaction.cpp.i
.PHONY : SmartHomeTemperature/Whatsapp/Whatsapp_reaction.cpp.i

SmartHomeTemperature/Whatsapp/Whatsapp_reaction.s: SmartHomeTemperature/Whatsapp/Whatsapp_reaction.cpp.s
.PHONY : SmartHomeTemperature/Whatsapp/Whatsapp_reaction.s

# target to generate assembly for a file
SmartHomeTemperature/Whatsapp/Whatsapp_reaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/Whatsapp/Whatsapp_reaction.cpp.s
.PHONY : SmartHomeTemperature/Whatsapp/Whatsapp_reaction.cpp.s

SmartHomeTemperature/smarthometemperature.o: SmartHomeTemperature/smarthometemperature.cpp.o
.PHONY : SmartHomeTemperature/smarthometemperature.o

# target to build an object file
SmartHomeTemperature/smarthometemperature.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/smarthometemperature.cpp.o
.PHONY : SmartHomeTemperature/smarthometemperature.cpp.o

SmartHomeTemperature/smarthometemperature.i: SmartHomeTemperature/smarthometemperature.cpp.i
.PHONY : SmartHomeTemperature/smarthometemperature.i

# target to preprocess a source file
SmartHomeTemperature/smarthometemperature.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/smarthometemperature.cpp.i
.PHONY : SmartHomeTemperature/smarthometemperature.cpp.i

SmartHomeTemperature/smarthometemperature.s: SmartHomeTemperature/smarthometemperature.cpp.s
.PHONY : SmartHomeTemperature/smarthometemperature.s

# target to generate assembly for a file
SmartHomeTemperature/smarthometemperature.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/SmartHomeTemperature/smarthometemperature.cpp.s
.PHONY : SmartHomeTemperature/smarthometemperature.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

yocto-gui-cmake_autogen/mocs_compilation.o: yocto-gui-cmake_autogen/mocs_compilation.cpp.o
.PHONY : yocto-gui-cmake_autogen/mocs_compilation.o

# target to build an object file
yocto-gui-cmake_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/yocto-gui-cmake_autogen/mocs_compilation.cpp.o
.PHONY : yocto-gui-cmake_autogen/mocs_compilation.cpp.o

yocto-gui-cmake_autogen/mocs_compilation.i: yocto-gui-cmake_autogen/mocs_compilation.cpp.i
.PHONY : yocto-gui-cmake_autogen/mocs_compilation.i

# target to preprocess a source file
yocto-gui-cmake_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/yocto-gui-cmake_autogen/mocs_compilation.cpp.i
.PHONY : yocto-gui-cmake_autogen/mocs_compilation.cpp.i

yocto-gui-cmake_autogen/mocs_compilation.s: yocto-gui-cmake_autogen/mocs_compilation.cpp.s
.PHONY : yocto-gui-cmake_autogen/mocs_compilation.s

# target to generate assembly for a file
yocto-gui-cmake_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yocto-gui-cmake.dir/build.make CMakeFiles/yocto-gui-cmake.dir/yocto-gui-cmake_autogen/mocs_compilation.cpp.s
.PHONY : yocto-gui-cmake_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... yocto-gui-cmake_autogen"
	@echo "... yocto-gui-cmake"
	@echo "... SmartHomeLeds/smarthome_leds.o"
	@echo "... SmartHomeLeds/smarthome_leds.i"
	@echo "... SmartHomeLeds/smarthome_leds.s"
	@echo "... SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.o"
	@echo "... SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.i"
	@echo "... SmartHomeTemperature/HumadityTemperature_sensor/dht11_sensor.s"
	@echo "... SmartHomeTemperature/LCD/LCD.o"
	@echo "... SmartHomeTemperature/LCD/LCD.i"
	@echo "... SmartHomeTemperature/LCD/LCD.s"
	@echo "... SmartHomeTemperature/Mail/Mail_reaction.o"
	@echo "... SmartHomeTemperature/Mail/Mail_reaction.i"
	@echo "... SmartHomeTemperature/Mail/Mail_reaction.s"
	@echo "... SmartHomeTemperature/Notifier/Notifier.o"
	@echo "... SmartHomeTemperature/Notifier/Notifier.i"
	@echo "... SmartHomeTemperature/Notifier/Notifier.s"
	@echo "... SmartHomeTemperature/Observer/Observer.o"
	@echo "... SmartHomeTemperature/Observer/Observer.i"
	@echo "... SmartHomeTemperature/Observer/Observer.s"
	@echo "... SmartHomeTemperature/WeatherStatus/WeatherStatus.o"
	@echo "... SmartHomeTemperature/WeatherStatus/WeatherStatus.i"
	@echo "... SmartHomeTemperature/WeatherStatus/WeatherStatus.s"
	@echo "... SmartHomeTemperature/Whatsapp/Whatsapp_reaction.o"
	@echo "... SmartHomeTemperature/Whatsapp/Whatsapp_reaction.i"
	@echo "... SmartHomeTemperature/Whatsapp/Whatsapp_reaction.s"
	@echo "... SmartHomeTemperature/smarthometemperature.o"
	@echo "... SmartHomeTemperature/smarthometemperature.i"
	@echo "... SmartHomeTemperature/smarthometemperature.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... yocto-gui-cmake_autogen/mocs_compilation.o"
	@echo "... yocto-gui-cmake_autogen/mocs_compilation.i"
	@echo "... yocto-gui-cmake_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

